name: Quarterly Release
on:
  schedule:
    - cron: '0 0 1 */3 *'  # At 00:00 on day-of-month 1 in every 3rd month
  release:
  workflow_dispatch:

jobs:
  #
  # Build jobs
  #
  install-alma-lib:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 21
      # Install alma-lib
      - name: build, test, and install alma-lib
        run: ./gradlew --info --build-file alma-lib/build.gradle clean build test publishToMavenLocal
      # Upload alma-lib artifact
      - uses: actions/upload-artifact@v6
        with:
          name: alma-lib
          path: /home/runner/.m2/repository/org/opencadc/alma-lib

  #
  # Build individual services
  #
  build-services:
    strategy:
      matrix:
        service:
          - name: cone
            artifact: cone
          - name: datalink
            artifact: datalink
          - name: sia
            artifact: sia2
          - name: tap
            artifact: tap
          - name: soda
            artifact: soda
          - name: reg
            artifact: reg
          - name: data
            artifact: data
    uses: ./.github/workflows/gradle-build.yml
    needs: install-alma-lib
    with:
      name: ${{ matrix.service.name }}
      artifact-name: ${{ matrix.service.artifact }}

  # Create tag here to tag repository once.
  release-tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.quarter-tag.outputs.tag }}
    steps:
      - name: Compute quarterly tag
        id: quarter-tag
        run: |
          YEAR=$(date -u +%Y)
          MONTH=$(date -u +%m)
          Q=$(( (10#$MONTH - 1) / 3 + 1 ))
          echo "tag=quarter-${YEAR}Q${Q}" >> $GITHUB_OUTPUT

  package-services:
    strategy:
      matrix:
        service:
          - name: cone
            artifact: cone
          - name: datalink
            artifact: datalink
          - name: sia
            artifact: sia2
          - name: tap
            artifact: tap
          - name: soda
            artifact: soda
          - name: reg
            artifact: reg
          - name: data
            artifact: data
    uses: ./.github/workflows/docker-build-publish.yml
    needs:
      - build-services
      - release-tag
    with:
      name: ${{ matrix.service.name }}
      artifact-name: ${{ matrix.service.artifact }}
      tag: ${{ needs.release-tag.outputs.tag }}
    secrets: inherit

  tag-release:
    runs-on: ubuntu-latest
    needs: release-tag
    steps:
      - name: Checkout for tagging
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.ref }}
          fetch-depth: 0
      - name: Tag repository
        run: |
          git tag ${{ needs.release-tag.outputs.tag }}
#          git push origin ${{ needs.release-tag.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}