name: Quarterly Release
on:
  schedule:
    - cron: '0 0 1 */3 *'  # At 00:00 on day-of-month 1 in every 3rd month

  # Only run on published releases to prevent several pipelines triggering
  release:
    types: [published]

  workflow_dispatch:

jobs:
  #
  # Build jobs
  #
  install-alma-lib:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 21
      # Install alma-lib
      - name: build, test, and install alma-lib
        run: ./gradlew --info --build-file alma-lib/build.gradle clean build test publishToMavenLocal
      # Upload alma-lib artifact
      - uses: actions/upload-artifact@v6
        with:
          name: alma-lib
          path: /home/runner/.m2/repository/org/opencadc/alma-lib

  #
  # Build individual services
  #
  build-services:
    strategy:
      matrix:
        service:
          - name: cone
            artifact: cone
          - name: datalink
            artifact: datalink
          - name: sia
            artifact: sia2
          - name: tap
            artifact: tap
          - name: soda
            artifact: soda
          - name: reg
            artifact: reg
          - name: data
            artifact: data
    uses: ./.github/workflows/gradle-build.yml
    needs: install-alma-lib
    with:
      name: ${{ matrix.service.name }}
      artifact-name: ${{ matrix.service.artifact }}

  # Create tag here to tag repository once.
  release-tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.quarter-tag.outputs.tag }}
    steps:
      - name: Compute quarterly tag
        id: quarter-tag
        run: |
          YEAR=$(date -u +%Y)
          MONTH=$(date -u +%m)
          Q=$(( (10#$MONTH - 1) / 3 + 1 ))
          echo "tag=${YEAR}q${Q}" >> $GITHUB_OUTPUT

  package-services:
    strategy:
      matrix:
        service:
          - name: cone
            artifact: cone
          - name: datalink
            artifact: datalink
          - name: sia
            artifact: sia2
          - name: tap
            artifact: tap
          - name: soda
            artifact: soda
          - name: reg
            artifact: reg
          - name: data
            artifact: data
    uses: ./.github/workflows/docker-build-publish.yml
    needs:
      - build-services
      - release-tag
    with:
      name: ${{ matrix.service.name }}
      artifact-name: ${{ matrix.service.artifact }}
      tag: ${{ needs.release-tag.outputs.tag }}
    secrets: inherit

  tag-release:
    runs-on: ubuntu-latest
    needs:
      - build-services
      - release-tag
      - package-services
    steps:
      - name: Checkout for tagging
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - name: Tag repository
        run: |
          git tag ${{ needs.release-tag.outputs.tag }}
          git push origin ${{ needs.release-tag.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  slack-release-notification:
    runs-on: ubuntu-latest
    needs:
      - tag-release
    steps:
      - name: Post message to a Slack channel
        uses: slackapi/slack-github-action@v2.1.1
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: ${{ secrets.SLACK_CHANNEL_ID }}
            text: "ALMA Service Release for ${{ needs.release-tag.outputs.tag }}"
            blocks:
              - type: "header"
                text:
                  type: "plain_text"
                  text: ":rocket: New ALMA IVOA Services quarterly release for ${{ needs.release-tag.outputs.tag }} is now available!"
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: ":wave:<https://github.com/opencadc|OpenCADC> has pushed the following Images to <https://hub.docker.com/orgs/opencadc/|OpenCADC Docker Hub>:"
              - type: "table"
                column_settings:
                  - is_wrapped: true
                rows:
                  - type: "raw_text",
                    text: "Image Tag"
                  - type: "raw_text",
                    text: "opencadc/alma-cone:${{ needs.release-tag.outputs.tag }}"
                  - type: "raw_text",
                    text: "opencadc/alma-datalink:${{ needs.release-tag.outputs.tag }}"
                  - type: "raw_text",
                    text: "opencadc/alma-sia:${{ needs.release-tag.outputs.tag }}"
                  - type: "raw_text",
                    text: "opencadc/alma-tap:${{ needs.release-tag.outputs.tag }}"
                  - type: "raw_text",
                    text: "opencadc/alma-soda:${{ needs.release-tag.outputs.tag }}"
                  - type: "raw_text",
                    text: "opencadc/alma-reg:${{ needs.release-tag.outputs.tag }}"
                  - type: "raw_text",
                    text: "opencadc/alma-data:${{ needs.release-tag.outputs.tag }}"
